openai/openai-node

README.md
Updates the README to reference our newly released model, `text-davinci-003`.
=> Update README for text-davinci-003

README.md
As we all know, the openai platform moved out of beta and changed the URL... This change would prevent redirects!
=> Docs: upgraded `beta.openai.com` -> `platform.openai.com` to prevent unnecessary redirects

README.md
It can be pretty annoying to use the built in copy command in Github and get the $ sign with the copy and end up with this in the terminal:
=> Remove $ from npm install command

src/index.ts, tests/lib/azure.test.ts
Azure changed their mind and now the request path of the Batch API doesn't reference deployment names.
=> chore(azure): batch API is not a deployments endpoint

src/resources/beta/vector-stores/file-batches.ts
better error message for https://github.com/openai/openai-node/issues/805
=> fix(vectorStores): correctly handle missing files in uploadAndPoll

src/_vendor/zod-to-json-schema/Options.ts, src/_vendor/zod-to-json-schema/README.md, src/_vendor/zod-to-json-schema/Refs.ts, src/_vendor/zod-to-json-schema/parseDef.ts, src/_vendor/zod-to-json-schema/parsers/nullable.ts, src/_vendor/zod-to-json-schema/util.ts, src/_vendor/zod-to-json-schema/zodToJsonSchema.ts, src/helpers/zod.ts, tests/lib/__snapshots__/parser.test.ts.snap, tests/lib/parser.test.ts, tests/utils/mock-snapshots.ts
Fixes how `$ref`s are created by changing it from using references like `#/definitions/user/properties/name` to extracting it to a top-level definition, e.g. `#/definitions/user_properties_name`.
This is very ugly... but I'd rather guarantee the definition will always be unique 🤷 
I think	this doesn't really work correctly for nested refs, we're overly duplicative :(
=> Various fixes for JSON Schema resolving

src/_vendor/zod-to-json-schema/zodToJsonSchema.ts, tests/lib/__snapshots__/parser.test.ts.snap, tests/lib/parser.test.ts
=> fix(helpers/zod): nested union schema extraction

src/_vendor/zod-to-json-schema/Options.ts, src/_vendor/zod-to-json-schema/zodToJsonSchema.ts, tests/lib/__snapshots__/parser.test.ts.snap, tests/lib/parser.test.ts
copy of #990 with some minor changes
=> fix(json-schema): correct handling of nested recursive schemas

src/index.ts, tests/lib/azure.test.ts
The AAD token may need to be refreshed between retries so this fix makes sure to always call the token provider irrespective of whether the authorization header is being set.
=> [Azure] Refresh AAD token on retry

src/lib/AssistantStream.ts
Initial commit from: https://github.com/openai/openai-node/pull/866
refactored the logic slightly
=> fix(assistants): correctly accumulate tool calls when streaming

src/lib/ChatCompletionRunner.ts, tests/lib/ChatCompletionRunFunctions.test.ts
Closes https://github.com/openai/openai-node/issues/994
This is techincally a breaking change but the helpers are still in beta.
=> fix: runTools without stream should not emit user message events

src/resources/beta/chat/completions.ts
closes #1057 
You can now do this:
```ts
const { data: completion, response } = await client.beta.chat.completions
.parse({
model: 'gpt-4o-2024-08-06',
messages: [
{ role: 'system', content: 'You are a helpful math tutor.' },
{ role: 'user', content: 'solve 8x + 31 = 2' },
],
response_format: zodResponseFormat(MathResponse, 'math_response'),
})
.withResponse();
```
=> feat(structured outputs): support accessing raw responses

examples/tool-calls-stream.ts, package.json, src/_vendor/partial-json-parser/README.md, src/_vendor/partial-json-parser/parser.ts, tests/_vendor/partial-json-parser/partial-json-parsing.test.ts, yarn.lock
This PR refactors the partial JSON parser we use from https://www.npmjs.com/package/partial-json-parser to https://www.npmjs.com/package/partial-json so that we can parse unterminated strings.
For example:
```
content: {"steps":[{"explanation":"Identifying
parsed: { steps: [ { explanation: 'Identifying' } ] }
content: {"steps":[{"explanation":"Identifying basic
parsed: { steps: [ { explanation: 'Identifying basic' } ] }
content: {"steps":[{"explanation":"Identifying basic climate
parsed: { steps: [ { explanation: 'Identifying basic climate' } ] }
```
=> fix(partial json): parse unterminated strings

src/resources/beta/chat/completions.ts
See comment here https://github.com/openai/openai-node/pull/1064#discussion_r1757724572
=> fix(runTools): correct request options type

README.md, src/core.ts, tests/responses.test.ts, tests/utils/typing.ts
=> feat(client): add ._request_id property to object responses

src/resources/audio/audio.ts, src/resources/audio/transcriptions.ts, src/resources/audio/translations.ts
v4.66.0 wasn't actually released due to a bug that wasn't found until release.
This PR:
- works around a bug in our deno build script
- adds fallback overload variants for audio transcriptions / translations
=> fix(audio): add fallback overload types

README.md
- [Y] I understand that this repository is auto-generated and my pull request may not be merged
Fixed an incorrect param in README. 
This is the same incorrect referencing as in #1199 
The official doc [https://platform.openai.com/docs/assistants/tools/file-search#step-2-upload-files-and-add-them-to-a-vector-store](here) also heeds to be changed.
=> docs(readme): fix incorrect fileBatches.uploadAndPoll params

README.md
=> docs(README): fix helpers section links

README.md
Correct the example link for the Realtime API to point to the appropriate websocket file.
=> docs(readme): fix Realtime API example link

README.md, examples/azure/chat.ts, examples/azure/realtime/websocket.ts, examples/azure/realtime/ws.ts, examples/package.json, src/beta/realtime/internal-base.ts, src/beta/realtime/websocket.ts, src/beta/realtime/ws.ts, src/index.ts
In order to do so, this PR adds an azure factory method to `OpenAIRealtimeWebSocket` and `OpenAIRealtimeWS` classes that can handle asynchronous operations required during WebSocket connection setup.
- Previously, the WebSocket connection was established in the class constructor, which could not handle async operations like fetching Azure AD tokens.
- The new `azure` method enables asynchronous fetching of the Azure AD token and then pass it to the class constructor.
- Adds a `_getAzureADToken` method in the `AzureOpenAI` class to provide refreshed Azure AD tokens.
=> feat(azure): Realtime API support

examples/azure/realtime/ws.ts, examples/realtime/ws.ts
Remove a duplicate send request for `session.update` event.
=> fix(examples/realtime): remove duplicate `session.update` call

src/beta/realtime/websocket.ts
The [WebSocket spec at WHATWG](https://websockets.spec.whatwg.org/#ref-for-dom-websocket-websocket%E2%91%A0) indicates that the `url` parameter of the WebSocket constructor is a string. Some implementations (like Chrome) will accept a URL object, but calling .toString() should work for all cases.
Fixes #1323.
=> fix(realtime): call .toString() on WebSocket url

.github/workflows/ci.yml, .gitignore, ecosystem-tests/cli.ts
We weren't running the ecosystem tests directly in this repository... this would've caught the `v4.85.0` bug.
=> CI: add ecosystem tests

src/lib/parser.ts, src/resources/beta/chat/completions.ts, tests/lib/ChatCompletionRunFunctions.test.ts, tests/lib/ChatCompletionStream.test.ts, tests/lib/parser.test.ts
The current behaviour of defaulting to an empty array breaks sending the message back to the API
```
400 Invalid 'messages[1].tool_calls': empty array. Expected an array with minimum length 1, but got an empty array instead.
```
=> fix(parsing): remove tool_calls default empty array

src/core.ts, src/resources/embeddings.ts, tests/api-resources/embeddings.test.ts
Requesting base64 encoded embeddings returns smaller body sizes, on average ~60% smaller than float32 encoded. In other words, the size of the response body containing embeddings in float32 is ~2.3x bigger than base64 encoded embedding.
Closes #1310
We always request embedding creating encoded as base64, and then decoded them to float32 based on the user's provided encoding_format parameter.
After running a few [benchmarks](https://github.com/manekinekko/rich-bench-node), requesting base64 encoded embeddings returns smaller body sizes, on average **~60% smaller** than float32 encoded. In other words, the size of the response body containing embeddings in float32 is **~2.3x bigger** than base64 encoded embedding.
This performance improvement could translate to:
- ✅ Faster HTTP responses
- …
=> perf(embedding): default embedding creation to base64

src/_vendor/zod-to-json-schema/parsers/object.ts, tests/helpers/zod.test.ts
The API doesn't support optional fields and the SDK is accidentally marking all fields as `required`, even when they've been marked with `.optional()`.
Fixing this would be a breaking change, so we're adding a warning and fixing this properly in v5.
=> fix(zod): warn on optional field usage

src/lib/ResponsesParser.ts
Enable lib clients to use this ParseableToolsParams definition
Expose ParseableToolsParams type
Hey, I was just trying to use this definition to create a "tools" variable with type annotation, but then I noticed it's not exported by this lib.
=> fix(types): export ParseableToolsParams

helpers.md, realtime.md
- Corrected a typo in the helper documentation so it now reads “automatically convert the model” rather than “conver the model”
- Fixed the spelling of “appropriately” in the realtime error handling section for clarity
=> docs: fix typos in helpers and realtime

src/_vendor/zod-to-json-schema/parsers/optional.ts, tests/helpers/zod.test.ts
- Adjusted optional field handling so that JSON Schema generation no longer emits redundant “not” constraints when an optional property is nested inside an object. The parser now checks that the current path begins with the property path before omitting the “not” clause
- Updated the test snapshot to match the corrected schema output, where optional nullable enums only include the union of the enum type and null without the extra “not” block
Fixes #1365
=> fix(zod): avoid adding redundant `not` to optional schemas

src/azure.ts, src/client.ts, tests/lib/azure.test.ts
Fixes https://github.com/openai/openai-node/issues/1633
Adds back support for API keys in the `AzureOpenAI` client.
=> fix(azure): correctly send API key
